const API_KEY = "032a51d75439320da927942f2f2a199a";


// Actions
const ADD_MOVIE_TO_LIST = "ADD_MOVIE_TO_LIST";

const CREATE_LIST = "CREATE_LIST";

const GET_LOCALSTORAGE_VALUE = "GET_LOCALSTORAGE_VALUE";

const REMOVE_MOVIE_FROM_LIST = "REMOVE_MOVIE_FROM_LIST";


export { API_KEY, ADD_MOVIE_TO_LIST, CREATE_LIST, GET_LOCALSTORAGE_VALUE, REMOVE_MOVIE_FROM_LIST }